Fix Makefile
openshift/osd-utils-cli pull request #71
Opened 2020-10-10 18:41 UTC by cblecker

Fixing a bunch of the boilerplate Makefile stuff to be less complex. This also fixes compilation on darwin, because go is smart enough to always use the current GOOS/GOARCH, so we don't need to hard code this to linux.

2020-10-12 12:08 UTC, iamkirkbater requested changes
One small change, other than that it lgtm.

2020-10-12 12:08 UTC, iamkirkbater commented on Makefile
> +	$(GO) test ${BUILDFLAGS} ./... -covermode=atomic -coverpkg=./...
I'm getting the following error with this:

```> make test
test  ./... -covermode=atomic -coverpkg=./...
/bin/sh: line 0: test: -covermode=atomic: binary operator expected
make: *** [test] Error 2
```

2020-10-12 12:08 UTC, iamkirkbater commented on Makefile
> +	$(GO) test ${BUILDFLAGS} ./... -covermode=atomic -coverpkg=./...
Ahh, 

```suggestion
	go test ${BUILDFLAGS} ./... -covermode=atomic -coverpkg=./...
```

2020-10-13 17:29 UTC, iamkirkbater approved these changes

2020-10-13 17:32 UTC, clcollins reviewed
/lgtm

2020-10-13 17:46 UTC, iamkirkbater commented
/hold cancel

2020-10-13 17:53 UTC, merged